Repository prgrms-fe-devcourse/FES-5-Project2-TEAM-1, pull requests merged in 2025-07, with the labels that each got.

#43 사이드바 호버 ui개선
  src/components/Layout/LeftSidebar.module.css
  src/components/Layout/LeftSidebar.tsx
Labels: 💫Feat

#47 Feature/스터디 가입 정보 채널
  public/icons/channelmember.svg
  public/icons/clock.svg
  public/icons/map-marker-line.svg
  public/images/map.png
  public/images/thumb.png
  src/App.css
  src/App.tsx
  src/components/Layout/LeftSidebar.module.css
  src/components/Layout/LeftSidebar.tsx
  src/components/Layout/RightSidebar.tsx
  src/components/Layout/card.module.css
  src/components/Layout/rightsidebar.module.css
  src/pages/Study/StudyJoinInfomation.module.css
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/components/ChannelComment.module.css
  src/pages/Study/components/ChannelComment.tsx
  src/pages/Study/components/Cruitmember.module.css
  src/pages/Study/components/Cruitmember.tsx
Labels: 💫Feat

#48 Feature/board write
  package-lock.json
  package.json
  public/icons/Calendar.png
  public/icons/Code.png
  public/icons/Link.png
  public/icons/Picture.png
  public/icons/place.png
  src/pages/BoardForm/BoardForm.module.css
  src/pages/BoardForm/BoardForm.tsx
  src/pages/BoardForm/components/BoardHashTag.tsx
  src/pages/BoardForm/components/BoardOptionSub.tsx
  src/pages/BoardForm/components/BoardOptions.tsx
  src/pages/BoardForm/components/BoardPreview.tsx
  src/pages/BoardForm/components/BoardWriteForm.tsx
  src/pages/BoardForm/components/markdown.module.css
  src/utils/debounce.ts
Labels: 💫Feat

#49 study/스터디 가입한채널
  public/icons/comment.svg
  public/icons/ellipsis.svg
  src/App.css
  src/App.tsx
  src/components/Layout/LeftSidebar.module.css
  src/pages/Study/StudyMemberChannel.module.css
  src/pages/Study/StudyMemberChannel.tsx
  src/pages/Study/components/Cruitmember.module.css
  src/pages/Study/components/Recomment.module.css
  src/pages/Study/components/Recomment.tsx
  src/pages/Study/components/StudyMember.module.css
  src/pages/Study/components/StudyMember.tsx
  src/pages/Study/components/StudyMemberChannelContent.module.css
  src/pages/Study/components/StudyMemberChannelContent.tsx
  src/pages/Study/components/Thread.module.css
  src/pages/Study/components/Thread.tsx
  src/pages/Study/components/ThreadList.module.css
  src/pages/Study/components/ThreadList.tsx
  src/pages/Study/studychannel.module.css
  src/style/reset.css
Labels: 💫Feat

#50 Feature/좋아요,스크랩기능
  public/icons/likeActive.png
  public/icons/scraplittleActive.png
  src/App.tsx
  src/components/Layout/Card.tsx
  src/components/Layout/LeftSidebar.tsx
  src/components/Layout/RightSidebar.tsx
  src/components/Layout/card.module.css
  src/pages/Study/StudyChannel.tsx
  src/supabase/database.types.ts
  src/supabase/supabase.ts
Labels: 💫Feat

#52 style/ 사이드바 안밀리게 개선
  src/App.css
  src/App.tsx
  src/components/Layout/LeftSidebar.module.css
  src/components/Layout/rightsidebar.module.css
  src/pages/Study/StudyJoinInfomation.module.css
  src/pages/Study/StudyJoinInfomation.tsx
Labels: 🐞bug

#54 Feature/mypage top2
  public/icons/edit.svg
  public/icons/edit_pencil.svg
  public/images/default_cover.png
  src/App.tsx
  src/pages/Mypage/MypageDetails.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageInterest.tsx
  src/pages/Mypage/MypageName.tsx
  src/pages/Mypage/MypageProfile.tsx
  src/pages/Mypage/MypageSocial.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/BackgroundEdit.tsx
  src/pages/Mypage/mypage.tsx
  src/supabase/database.types.ts
  src/utils/Alert.module.css
  src/utils/Alert.tsx
Labels: 💫Feat

#58 feat. scrap, post 기능 추가, css 레이아웃 전체 수정
  src/App.css
  src/App.tsx
  src/components/Layout/LeftSidebar.module.css
  src/components/Layout/rightsidebar.module.css
  src/pages/Mypage/MypageBottom.module.css
  src/pages/Mypage/MypagePost.tsx
  src/pages/Mypage/MypageScrap.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/MypageChannel.module.css
  src/pages/Mypage/components/MypageChannel.tsx
  src/pages/Mypage/components/MypagePeerReview.module.css
  src/pages/Mypage/components/MypagePeerReview.tsx
  src/pages/Mypage/components/MypagePost.module.css
  src/pages/Mypage/components/MypagePost.tsx
  src/pages/Mypage/components/MypageScrap.module.css
  src/pages/Mypage/components/MypageScrap.tsx
  src/pages/Mypage/components/MypageSwiper.css
  src/pages/Mypage/mypage.tsx
Labels: 💫Feat

#60 Feature/mainpage
  public/images/banner.png
  public/images/서치이미지.png
  src/App.tsx
  src/components/Layout/LeftSidebar.module.css
  src/components/Layout/rightSidebar.module.css
  src/main.tsx
  src/pages/Login/login.tsx
  src/pages/Mainpage/BannerSection.module.css
  src/pages/Mainpage/BannerSection.tsx
  src/pages/Mainpage/Footer.module.css
  src/pages/Mainpage/Footer.tsx
  src/pages/Mainpage/MainContent.module.css
  src/pages/Mainpage/MainContent.tsx
  src/pages/Mainpage/MainStudyCard.module.css
  src/pages/Mainpage/MainStudyCard.tsx
  src/pages/Mainpage/NewsSection.module.css
  src/pages/Mainpage/NewsSection.tsx
  src/supabase/database.types.ts
  src/supabase/supabase.ts
Labels: 💫Feat

#61 Feature/study 검색,페이지네이션기능
  src/App.tsx
  src/components/Layout/Card.tsx
  src/components/Layout/card.module.css
  src/main.tsx
  src/pages/Study/StudyChannel.tsx
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/StudyMemberChannel.tsx
  src/pages/Study/components/ChannelComment.module.css
  src/pages/Study/components/ChannelComment.tsx
  src/pages/Study/components/Cruitmember.module.css
  src/pages/Study/components/Cruitmember.tsx
  src/pages/Study/components/utills/DdayCounter.ts
  src/router/router.tsx
  src/supabase/database.types.ts
  src/utils/NavLink.tsx
  src/utils/utils.tsx
Labels: 💫Feat

#63 Feature/mypage top2
  public/icons/edit_close.svg
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageProfile.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/BackgroundEdit.tsx
  src/pages/Mypage/components/ProfileEdit.module.css
  src/pages/Mypage/components/ProfileEdit.tsx
  src/utils/Alert.tsx
Labels: 💫Feat

#70 feature/ 전역에서 쓸 수 있는 react-toastify 라이브러리를 가져왔습니다.
  package-lock.json
  package.json
  src/App.tsx
  src/components/ToastContext.ts
  src/components/ToastOverride.css
  src/components/ToastProvider.tsx
  src/main.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageDetails.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageName.tsx
  src/pages/Mypage/MypageProfile.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/BackgroundEdit.tsx
  src/pages/Mypage/components/ProfileEdit.tsx
  src/utils/Alert.module.css
  src/utils/Alert.tsx
  src/utils/useToast.tsx
Labels: 💫Feat

#74 Feature. mypage bottom component 수정 및 top btn 추가
  src/assets/topButton.png
  src/components/ToastOverride.css
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/components/MoveToTop.module.css
  src/pages/Mypage/components/MoveToTop.tsx
  src/pages/Mypage/components/MypageChannel.module.css
  src/pages/Mypage/components/MypageChannel.tsx
  src/pages/Mypage/components/MypagePeerReview.module.css
  src/pages/Mypage/components/MypagePeerReview.tsx
  src/pages/Mypage/components/MypagePost.module.css
  src/pages/Mypage/components/MypagePost.tsx
  src/pages/Mypage/components/MypageScrap.module.css
  src/pages/Mypage/components/MypageScrap.tsx
  src/pages/Mypage/components/MypageSocialConvert.module.css
  src/pages/Mypage/components/MypageSocialConvert.tsx
  src/pages/Mypage/components/MypageSwiper.css
  src/supabase/database.types.ts
Labels: 💫Feat

#84 Mypage top3
  package-lock.json
  package.json
  public/icons/closed_eye.svg
  public/icons/eye.svg
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageDetails.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageName.tsx
  src/pages/Mypage/MypageTop.module.css
  src/supabase/database.types.ts
Labels: 💫Feat

#86 Feature/map api
  package-lock.json
  package.json
  public/icons/Close.svg
  public/icons/check.svg
  public/images/file-upload.png
  public/images/no_image.png
  src/@types/kakao.maps.d.ts
  src/components/DragDropFile.module.css
  src/components/DragDropFile.tsx
  src/components/HashTag.module.css
  src/components/MapSearchPopup.module.css
  src/components/MapSearchPopup.tsx
  src/components/MarkDownConvert.module.css
  src/components/MarkDownConvert.tsx
  src/components/context/useBoardContext.tsx
  src/components/context/useProfileImage.tsx
  src/pages/BoardForm/BoardForm.module.css
  src/pages/BoardForm/BoardForm.tsx
  src/pages/BoardForm/components/BoardEdit.module.css
  src/pages/BoardForm/components/BoardEdit.tsx
  src/pages/BoardForm/components/BoardOption.module.css
  src/pages/BoardForm/components/BoardOption.tsx
  src/pages/BoardForm/components/BoardOptionPreview.module.css
  src/pages/BoardForm/components/BoardOptionPreview.tsx
  src/pages/BoardForm/components/BoardOptionSub.tsx
  src/pages/BoardForm/components/BoardOptions.tsx
  src/pages/BoardForm/components/BoardPreview.module.css
  src/pages/BoardForm/components/BoardPreview.tsx
  src/pages/BoardForm/components/BoardWrite.module.css
  src/pages/BoardForm/components/BoardWrite.tsx
  src/pages/BoardForm/components/BoardWriteForm.tsx
  tsconfig.json
Labels: 💫Feat

#76 Feature. 관리탭 jsx(디자인만) 추가
  package-lock.json
  src/components/Layout/RightSidebar.tsx
  src/pages/Study/components/Approve.module.css
  src/pages/Study/components/Approve.tsx
  src/pages/Study/components/Management.module.css
  src/pages/Study/components/Management.tsx
  src/pages/Study/components/ManagementChannel.module.css
  src/pages/Study/components/ManagementChannel.tsx
  src/pages/Study/components/ManagementMembers.module.css
  src/pages/Study/components/ManagementMembers.tsx
  src/supabase/database.types.ts
Labels: 😎 Style

#90 Feature. mypage auth
  src/App.tsx
  src/components/Layout/RightSidebar.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/components/DeleteAccount.module.css
  src/pages/Mypage/components/DeleteAccount.tsx
  src/pages/Mypage/components/MoveToTop.module.css
  src/pages/Mypage/components/MoveToTop.tsx
  src/pages/Mypage/components/MypageChannel.tsx
  src/pages/Mypage/components/MypagePeerReview.tsx
  src/pages/Mypage/components/MypagePost.module.css
  src/pages/Mypage/components/MypagePost.tsx
  src/pages/Mypage/components/MypageScrap.tsx
  src/pages/Register.tsx
  src/supabase/database.types.ts
Labels: 🐞bug, 💫Feat, 😎 Style

#92 Feature/board write supabase
  package-lock.json
  package.json
  public/icons/Code.png
  public/icons/Code.svg
  public/icons/Link.png
  public/icons/Link.svg
  public/icons/Picture.png
  public/icons/Picture.svg
  public/icons/Quote.svg
  public/icons/bold.svg
  public/icons/cancelline.svg
  public/icons/h1.svg
  public/icons/h2.svg
  public/icons/h3.svg
  public/icons/italic.svg
  public/images/imageUpload.png
  src/@types/tagify-react.d.ts
  src/App.tsx
  src/components/DragDropFile.module.css
  src/components/DragDropFile.tsx
  src/components/HashTag.module.css
  src/components/HashTag.tsx
  src/components/MapSearchPopup.tsx
  src/components/context/useHashTag.tsx
  src/pages/BoardForm/BoardForm.tsx
  src/pages/BoardForm/BoardWrite.tsx
  src/pages/BoardForm/components/BoardButtonArea.module.css
  src/pages/BoardForm/components/BoardButtonArea.tsx
  src/pages/BoardForm/components/BoardEdit.module.css
  src/pages/BoardForm/components/BoardOption.module.css
  src/pages/BoardForm/components/BoardOption.tsx
  src/pages/BoardForm/components/BoardOptionPreview.module.css
  src/pages/BoardForm/components/BoardOptionPreview.tsx
  src/pages/BoardForm/components/BoardPreview.module.css
  src/pages/BoardForm/components/BoardWrite.module.css
  src/pages/BoardForm/components/BoardWrite.tsx
Labels: 💫Feat

#93 관심사 추가
  public/icons/back.svg
  public/icons/minus.svg
  public/icons/plus.svg
  src/components/ToastProvider.module.css
  src/components/data/interestData.json
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageDetails.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageInterest.tsx
  src/pages/Mypage/MypageName.tsx
  src/pages/Mypage/MypageSocial.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/InterestDropdown.module.css
  src/pages/Mypage/components/InterestDropdown.tsx
  src/pages/Mypage/components/ProfileEdit.module.css
  src/supabase/database.types.ts
Labels: 💫Feat

#94 Feature. 관리 메뉴 라우팅
  src/App.tsx
  src/pages/Study/StudyMemberChannel.module.css
  src/pages/Study/StudyMemberChannel.tsx
  src/pages/Study/components/Management.module.css
  src/pages/Study/components/Management.tsx
  src/pages/Study/components/ManagementChannel.tsx
  src/pages/Study/components/management/Approve.module.css
  src/pages/Study/components/management/Approve.tsx
  src/pages/Study/components/management/Management.module.css
  src/pages/Study/components/management/Management.tsx
  src/pages/Study/components/management/ManagementChannel.module.css
  src/pages/Study/components/management/ManagementChannel.tsx
  src/pages/Study/components/management/ManagementMembers.module.css
  src/pages/Study/components/management/ManagementMembers.tsx
  src/supabase/database.types.ts
Labels: 💫Feat

#96 Feature/board save
  src/auth/AuthProvider.tsx
  src/pages/BoardForm/BoardForm.module.css
  src/pages/BoardForm/BoardForm.tsx
  src/pages/BoardForm/components/BoardOption.tsx
Labels: 💫Feat

#97 Feature. sweetAlert 추가, 로그인/회원가입 페이지 css 수정
  package-lock.json
  package.json
  public/images/banner2.png
  public/images/loginbanner2.png
  public/images/nail.png
  public/images/successImg2.jpg
  src/App.css
  src/components/Layout/LeftSidebar.tsx
  src/components/Layout/RghtSidebar.module.css
  src/components/Layout/RightSidebar.tsx
  src/components/PasswordInput.module.css
  src/components/PasswordInput.tsx
  src/pages/Login/Login.module.css
  src/pages/Login/login.tsx
  src/pages/Mainpage/BannerSection.tsx
  src/pages/Mainpage/MainStudyCard.tsx
  src/pages/Mainpage/NewsSection.module.css
  src/pages/Register.module.css
  src/pages/Register.tsx
  src/style/sweetAlert.css
  src/utils/sweetAlert.tsx
Labels: 💫Feat

#98 Feature/가입 신청 승인 거절 기능
  src/App.css
  src/App.tsx
  src/components/Layout/Card.tsx
  src/components/Layout/RghtSidebar.module.css
  src/components/Layout/RightSidebar.tsx
  src/components/Layout/card.module.css
  src/pages/Study/StudyChannel.tsx
  src/pages/Study/StudyJoinInfomation.module.css
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/StudyMemberChannel.module.css
  src/pages/Study/StudyMemberChannel.tsx
  src/pages/Study/components/ChannelComment.tsx
  src/pages/Study/components/Thread.module.css
  src/pages/Study/components/Thread.tsx
  src/pages/Study/components/management/Approve.module.css
  src/pages/Study/components/management/Approve.tsx
  src/pages/Study/components/management/ManagementMembers.tsx
  src/pages/Study/studychannel.module.css
  src/supabase/database.types.ts
Labels: 💫Feat

#102 소셜 설정 기능 추가
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageInterest.tsx
  src/pages/Mypage/MypageSocial.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/MypageSocialConvert.tsx
Labels: 💫Feat

#101 Feature/managing channel
  src/auth/AuthProvider.tsx
  src/components/Layout/RightSidebar.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/components/DeleteAccount.module.css
  src/pages/Mypage/components/DeleteAccount.tsx
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/components/management/ManagementChannel.module.css
  src/pages/Study/components/management/ManagementChannel.tsx
  src/supabase/database.types.ts
Labels: 🐞bug, 💫Feat

#106 feat/authprovider 수정
  src/auth/AuthProvider.tsx
  src/pages/BoardForm/BoardWrite.tsx
Labels: 🛠️Fix

#108 style/ 로그인, 회원가입 페이지에서 메인페이지로 넘어가는 링크 생성
  src/pages/Login/Login.module.css
  src/pages/Login/login.tsx
  src/pages/Register.module.css
  src/pages/Register.tsx
Labels: 😎 Style

#109 Feature/login fix
  src/pages/BoardForm/BoardForm.tsx
  src/pages/BoardForm/BoardUpdate.tsx
  src/pages/BoardForm/components/BoardOptionPreview.tsx
Labels: 🛠️Fix

#110 Feature. management channel mypage bottom
  package-lock.json
  package.json
  public/images/online.png
  src/components/Layout/RightSidebar.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/components/MypageChannel.tsx
  src/pages/Mypage/components/MypagePeerReview.module.css
  src/pages/Mypage/components/MypagePeerReview.tsx
  src/pages/Mypage/components/MypagePost.module.css
  src/pages/Mypage/components/MypagePost.tsx
  src/pages/Mypage/components/MypageScrap.module.css
  src/pages/Mypage/components/MypageScrap.tsx
  src/pages/Mypage/components/MypageSocialConvert.tsx
  src/pages/Mypage/components/MypageSwiper.css
  src/pages/Study/StudyJoinInfomation.module.css
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/components/KakaoMap.tsx
  src/pages/Study/components/Project.module.css
  src/pages/Study/components/Project.tsx
  src/pages/Study/components/management/ManagementChannel.module.css
  src/pages/Study/components/management/ManagementChannel.tsx
Labels: 💫Feat, 😎 Style, 🛠️Fix

#111 마이페이지 관심사, 소셜 기능 리팩토링 + 애니메이션 추가
  public/icons/add.svg
  src/assets/facebook.png
  src/assets/line.png
  src/assets/linkedin.png
  src/assets/youtube.png
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageInterest.tsx
  src/pages/Mypage/MypageSocial.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/InterestDropdown.tsx
  src/pages/Mypage/components/MypageSocialConvert.tsx
Labels: 💫Feat

#113 Fix. kakao map script 렌더링 문제
  index.html
  src/components/Layout/RightSidebar.tsx
  src/components/context/useKakaoLoaderProvider.tsx
  src/main.tsx
  src/pages/Study/components/KakaoMap.tsx
  tsconfig.json
Labels: 🛠️Fix
