Repository prgrms-fe-devcourse/FES-5-Project2-TEAM-1, pull requests merged in 2025-08, with the labels that each got.

#119 fix & style. mypage bottom
  src/App.css
  src/components/Layout/RghtSidebar.module.css
  src/components/Layout/RightSidebar.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageInterest.tsx
  src/pages/Mypage/MypageSocial.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/MypageChannel.module.css
  src/pages/Mypage/components/MypageChannel.tsx
  src/pages/Mypage/components/MypagePeerReview.module.css
  src/pages/Mypage/components/MypagePeerReview.tsx
  src/pages/Mypage/components/MypagePost.module.css
  src/pages/Mypage/components/MypagePost.tsx
  src/pages/Mypage/components/MypageScrap.module.css
  src/pages/Mypage/components/MypageScrap.tsx
  src/pages/Mypage/components/MypageSwiper.css
Labels: 🐞bug, 😎 Style, 🛠️Fix

#122 가입자 목록 조회하는 기능 + 오른쪽 사이드바에서 상태변경 기능 + style
  public/icons/away.svg
  public/icons/dnd.svg
  public/icons/offline.svg
  public/icons/online.svg
  src/App.css
  src/auth/AuthProvider.tsx
  src/components/Layout/LeftSidebar.module.css
  src/components/Layout/LeftSidebar.tsx
  src/components/Layout/RghtSidebar.module.css
  src/components/Layout/RightSidebar.tsx
  src/components/UserList.module.css
  src/components/UserList.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageName.tsx
  src/pages/Mypage/components/MypagePeerReview.module.css
Labels: 💫Feat

#123 반응형작업 + ui개선 + scrap 에러 fix
  src/components/HashTag.module.css
  src/components/Layout/Card.tsx
  src/components/Layout/card.module.css
  src/pages/BoardForm/BoardForm.module.css
  src/pages/BoardForm/BoardForm.tsx
  src/pages/BoardForm/components/BoardButtonArea.module.css
  src/pages/BoardForm/components/BoardEdit.module.css
  src/pages/BoardForm/components/BoardOption.module.css
  src/pages/BoardForm/components/BoardOption.tsx
  src/pages/BoardForm/components/BoardOptionPreview.module.css
  src/pages/BoardForm/components/BoardOptionPreview.tsx
  src/pages/BoardForm/components/BoardPreview.module.css
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/components/ThreadList.tsx
Labels: 😎 Style, 🛠️Fix

#124 style/ 메인페이지 반응형 + 404페이지
  public/icons/notfound2.svg
  public/images/notfound.png
  src/App.css
  src/App.tsx
  src/pages/Login/Login.module.css
  src/pages/Mainpage/BannerSection.module.css
  src/pages/Mainpage/Footer.module.css
  src/pages/Mainpage/MainContent.module.css
  src/pages/Mainpage/MainStudyCard.module.css
  src/pages/Mainpage/NewsSection.module.css
  src/pages/Mainpage/NewsSection.tsx
  src/pages/NotFound.module.css
  src/pages/NotFound.tsx
  src/pages/Register.module.css
Labels: 😎 Style

#127 Feature/study join infomation page
  src/App.css
  src/App.tsx
  src/components/Calender.module.css
  src/components/Calender.tsx
  src/components/Layout/LeftSidebar.module.css
  src/components/Layout/LeftSidebar.tsx
  src/components/Layout/RghtSidebar.module.css
  src/components/Layout/RightSidebar.tsx
  src/pages/Mainpage/Footer.module.css
  src/pages/PeerReview/PeerReiview.tsx
  src/pages/PeerReview/PeerReveiw.module.css
  src/pages/Study/StudyJoinInfomation.module.css
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/components/management/Approve.tsx
  src/pages/Study/components/management/ManagementChannel.module.css
  src/pages/Study/components/management/ManagementChannel.tsx
  src/pages/Study/components/management/ManagementMembers.tsx
  src/pages/team/Team.module.css
  src/pages/team/Team.tsx
  src/supabase/database.types.ts
Labels: 💫Feat

#128 Mypage top3
  src/components/Layout/LeftSidebar.module.css
  src/components/Layout/RightSidebar.tsx
  src/components/UserList.module.css
  src/components/UserList.tsx
  src/pages/Login/login.tsx
  src/pages/Mypage/MypageTop.module.css
Labels: 🛠️Fix

#140 마이페이지 스타일
  src/App.css
  src/App.tsx
  src/components/Layout/RightSidebar.tsx
  src/components/UserList.tsx
  src/pages/Mainpage/Footer.module.css
  src/pages/Mypage/MypageDetails.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageName.tsx
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/MypagePeerReview.module.css
Labels: 🛠️Fix

#156 마이페이지 디폴트 이름 띄우기 + 마이페이지 수정칸에서 다른사람 페이지가면 수정칸보이는것
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/MypageName.tsx
Labels: 🛠️Fix

#158 fix/스터디채널 버그수정
  src/components/Layout/Card.tsx
  src/pages/PeerReview/PeerReiview.tsx
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/components/management/ManagementChannel.module.css
  src/pages/Study/components/management/ManagementChannel.tsx
  src/pages/Study/components/management/ManagementMembers.tsx
  src/supabase/database.types.ts
Labels: 🛠️Fix

#159 Fix/ 소셜, 관심사 없을 때 UI 추가, 소셜 링크 추가, 저장하고 수정 나가면 바로 렌더링 안되는 문제 해결
  src/pages/Mypage/MypageInterest.tsx
  src/pages/Mypage/MypageSocial.tsx
  src/pages/Mypage/MypageTop.module.css
Labels: 🛠️Fix

#166 Fix/메인페이지 NewsSection
  src/pages/Mainpage/MainContent.module.css
  src/pages/Mainpage/MainContent.tsx
  src/pages/Mainpage/NewsSection.module.css
Labels: 🛠️Fix

#173 Fix/ 피어온도 팝업 추가 + 나이 버그 해결 + 영민님 hashtag style width 변경
  src/App.tsx
  src/components/HashTag.module.css
  src/components/PeerReviewPopup.module.css
  src/components/PeerReviewPopup.tsx
  src/components/UserList.tsx
  src/pages/Mypage/MypageDetails.tsx
  src/pages/Mypage/components/ProfileEdit.tsx
Labels: 💫Feat, 🛠️Fix

#175 Fix/ 멤버 정원 버그 + 좌측 사이드바 팝업 다른 이름에 깔리는 버그
  src/components/UserList.module.css
  src/pages/Study/components/management/Approve.tsx
Labels: 🛠️Fix

#180 Fix/ 소셜 렌더링 바로 안되는거 버그
  src/pages/Mypage/MypageSocial.tsx
  src/pages/Mypage/components/MypageSocialConvert.tsx
Labels: 🛠️Fix

#188 Fix/ 가입한 사용자 상태변화 버그
  src/App.css
  src/components/UserList.tsx
  src/pages/Mypage/MypageSocial.tsx
Labels: 🛠️Fix

#190 fix/스레드 댓글 버그 픽스
  src/components/MapSearchPopup.tsx
  src/components/context/NotificationContext.tsx
  src/pages/BoardForm/components/BoardButtonArea.tsx
  src/pages/Mypage/components/MypageSocialConvert.tsx
  src/pages/Study/StudyJoinInfomation.tsx
  src/pages/Study/components/ChannelComment.tsx
  src/pages/Study/components/CommentItem.tsx
  src/pages/Study/components/Recomment.tsx
  src/pages/Study/components/Thread.tsx
  src/pages/Study/components/ThreadList.tsx
  src/pages/Study/components/ThreadReplyComponent.tsx
  src/pages/Study/components/management/Approve.tsx
  src/pages/team/Team.tsx
Labels: 🛠️Fix

#198 style. 마이페이지 상단 반응형 수정
  src/pages/Mypage/MypageDetails.tsx
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/BackgroundEdit.tsx
  src/pages/Mypage/components/ProfileEdit.module.css
  src/pages/Mypage/components/ProfileEdit.tsx
Labels: 😎 Style

#199 Fix. 수료증 사진 깨짐 수정
  src/pages/Admin/Admin.module.css
  src/pages/Admin/Admin.tsx
Labels: 🛠️Fix

#204 Fix/ 소셜인풋 포커스 스타일 픽스
  src/pages/Mypage/MypageEdit.module.css
Labels: 🛠️Fix

#205 fix. 스터디 홈 배너 z-index 수정, 전체 주석 삭제
  src/App.css
  src/components/Layout/RghtSidebar.module.css
  src/components/Layout/card.module.css
  src/pages/BoardForm/BoardForm.module.css
  src/pages/BoardForm/components/BoardOptionPreview.module.css
  src/pages/Mainpage/BannerSection.module.css
  src/pages/Mainpage/MainContent.module.css
  src/pages/Mainpage/NewsSection.module.css
  src/pages/Mypage/MypageEdit.module.css
  src/pages/Mypage/MypageTop.module.css
  src/pages/Mypage/components/MypagePeerReview.module.css
  src/pages/Mypage/components/MypageSwiper.css
  src/pages/Register.module.css
  src/pages/Study/StudyJoinInfomation.module.css
  src/pages/Study/StudyMemberChannel.module.css
  src/pages/Study/components/ChannelComment.module.css
  src/pages/Study/components/Project.module.css
  src/pages/Study/components/management/Approve.module.css
  src/pages/Study/components/management/Management.module.css
  src/pages/Study/components/management/ManagementChannel.module.css
  src/pages/Study/studychannel.module.css
Labels: 🛠️Fix

#206 닉네임 중복 체크
  src/pages/Mypage/MypageName.tsx
Labels: 💫Feat
